language: C++

dist: bionic

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.7
      env:
         - MATRIX_EVAL="CC=gcc-4.7 && CXX=g++-4.7"

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get -qq update
  - sudo apt-get install gfortran
  - sudo apt-get install liblzma-dev
  - wget https://zlib.net/zlib-1.2.11.tar.gz && tar -xvf zlib-1.2.11.tar.gz && cd zlib-1.2.11 && ./configure && sudo make && sudo make install && cd ../
  - wget https://ftp.pcre.org/pub/pcre/pcre-8.42.tar.gz && tar -xvf pcre-8.42.tar.gz && cd pcre-8.42 && ./configure --enable-utf8 --enable-unicode-properties && sudo make && sudo make install && cd ../
  - git clone git://github.com/PRL-PRG/R-dyntrace.git && cd R-dyntrace && ./build && cd ..

script: R-dyntrace/bin/R CMD INSTALL --build --with-keep.source .
